---
- name: Docker image creation playbook
  hosts: all
  tasks:
    - name: build docker image
      shell: docker build -t raiyan/sample-app:v1 .
      args:
        chdir: /apps

    - name: docker login
      shell: docker login -u raiyan -pDocker100%

    - name: push docker image
      shell: docker push raiyan/sample-app:v1

